// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBPmXqBGvzt0Cc_EpTqMO0mv8BgHB0IA',
    appId: '1:174057326350:web:f41857c882a1c1dea6395f',
    messagingSenderId: '174057326350',
    projectId: 'aslimaticapp-1188',
    authDomain: 'aslimaticapp-1188.firebaseapp.com',
    storageBucket: 'aslimaticapp-1188.firebasestorage.app',
    measurementId: 'G-QZQK8Y6LK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqAYNRTYoni1CFhfrxSAcbD6HJz_VUzNE',
    appId: '1:174057326350:android:71a7900a1f9bd3d7a6395f',
    messagingSenderId: '174057326350',
    projectId: 'aslimaticapp-1188',
    storageBucket: 'aslimaticapp-1188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIhHOYvmplOR8XojI-EiCIf0Y-ydi1hmk',
    appId: '1:174057326350:ios:99f7b615a1192eb3a6395f',
    messagingSenderId: '174057326350',
    projectId: 'aslimaticapp-1188',
    storageBucket: 'aslimaticapp-1188.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIhHOYvmplOR8XojI-EiCIf0Y-ydi1hmk',
    appId: '1:174057326350:ios:99f7b615a1192eb3a6395f',
    messagingSenderId: '174057326350',
    projectId: 'aslimaticapp-1188',
    storageBucket: 'aslimaticapp-1188.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBPmXqBGvzt0Cc_EpTqMO0mv8BgHB0IA',
    appId: '1:174057326350:web:c4cd06f20e446372a6395f',
    messagingSenderId: '174057326350',
    projectId: 'aslimaticapp-1188',
    authDomain: 'aslimaticapp-1188.firebaseapp.com',
    storageBucket: 'aslimaticapp-1188.firebasestorage.app',
    measurementId: 'G-ZPX6SL8HJF',
  );
}
